# # Allowed sources
# source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '10.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# project 'reactNativeKnock.xcodeproj'

# target 'reactNativeKnock' do
#   # As we use Swift, ensure that `use_frameworks` is enabled.
#   use_frameworks!


#   # React Native Datetime List Picker
#   pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'
#   # # React Native Vector Icons
#   # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#   # Your 'node_modules' directory is probably in the root of your project,
#   # but if not, adjust the `:path` accordingly
#   pod 'React', :path => '../node_modules/react-native/'
#   pod 'React-Core', :path => '../node_modules/react-native'
#   pod 'React-Core/DevSupport', :path => '../node_modules/react-native'
#   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native'

#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'


#   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#   pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

# end

# Allowed sources
source 'https://github.com/CocoaPods/Specs.git'

target 'MyApp' do
  # As we use Swift, ensure that `use_frameworks` is enabled.
  use_frameworks!

  # Specific iOS platform we are targetting
  platform :ios, '9.0'

  # Point to the installed version
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'

  # React/React-Native specific pods
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',      # Include this for RN >= 0.47
    'DevSupport',     # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',   # Needed for debugging
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end
